services:
  - type: static
    name: paymentflow
    buildCommand: npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_GA_ID
        sync: false
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
      - key: VITE_STRIPE_PUBLISHABLE_KEY
        sync: false
